### ISSUE TITLE
Assign group to new data

### ISSUE THREAD

**Issue by DSoudis** [alessandromagrini/gbmt#1]
Thanks for this great package!

Is it possible to use a fitted model to assign group membership to "unseen" data. I mean units that were not used during the fitting process. Predict works for trajectories not group assignment from what i can tell

**Comment by alessandromagrini** [comment]
Hi there, thank you for your appreciation. Yes, it is possible to predict posterior probabilities for a new datum. This feature, besides several other ones (different rescaling procedures and new graphical controls), will be available in the new release that should be ready in few days.

**Comment by DSoudis** [comment]
Great! Looking forward!
