### ISSUE TITLE
Error in rbind(deparse.level, ...) : numbers of columns of arguments do not match

### ISSUE THREAD

**Issue by zh-zhang1984** [alessandromagrini/gbmt#2]
Hi, I encounter following error in running our example, is there any hints for this? 
```
> head(Dat_long,10)
   PtID RCCtimes VentiParDays RR  TV    MV Pimax RSBI
1     1        1            2 15 333  5.00   -18   45
2     2        1            2 40 196  7.80   -10  204
3     2        2            9 33 227  7.50   -14    8
4     2        3            9 30 285  8.57   -20  105
5     2        4           16 33 349 11.50   -30   94
6     3        1            3 27 286  7.74   -40   94
7     4        1            1 24 302  7.25   -24   79
8     5        1            3 23 469  9.80   -30   53
9     5        2           13 14 371  5.20   -18   37
10    5        3           13 23 330  7.60   -20   69
> summary(Dat_long)
      PtID        RCCtimes          VentiParDays         RR              TV                 MV       
 18     :   5   Length:2843        Min.   : 1.00   Min.   : 6.00   Min.   :   0.042   Min.   : 0.32  
 84     :   5   Class :character   1st Qu.:11.00   1st Qu.:21.00   1st Qu.: 242.500   1st Qu.: 6.00  
 131    :   5   Mode  :character   Median :15.00   Median :25.00   Median : 315.000   Median : 7.80  
 201    :   5                      Mean   :15.24   Mean   :26.02   Mean   : 325.997   Mean   : 8.18  
 283    :   5                      3rd Qu.:19.00   3rd Qu.:30.00   3rd Qu.: 397.000   3rd Qu.:10.00  
 309    :   5                      Max.   :29.00   Max.   :77.00   Max.   :1280.000   Max.   :25.10  
 (Other):2813                                                                         NA's   :1      
     Pimax             RSBI        
 Min.   :-90.00   Min.   :   7.00  
 1st Qu.:-30.00   1st Qu.:  57.00  
 Median :-26.00   Median :  81.00  
 Mean   :-26.31   Mean   :  98.22  
 3rd Qu.:-20.00   3rd Qu.: 118.00  
 Max.   : -2.00   Max.   :1563.00  
 NA's   :12       NA's   :1        
> library(gbmt)
> mod_gbmt <- gbmt::gbmt(
  x.names=c("RR","TV","Pimax","MV","RSBI"), 
  unit="PtID", 
  time="VentiParDays", d=2, ng=3, 
  data=Dat_long, scaling=2
)
Error in rbind(deparse.level, ...) : numbers of columns of arguments do not match
5.
stop("numbers of columns of arguments do not match")
4.
rbind(deparse.level, ...)
3.
(function (..., deparse.level = 1) .Internal(rbind(deparse.level, ...)))(`1` = structure(list(PtID = structure(c(1L, 1L, 1L, 1L, 1L), class = "factor", .Label = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "14", "15", "16", ...
                                                                                                                                                                   2.
                                                                                                                                                                   do.call(rbind, lapply(split(data, data[, unit]), function(x) { cbind(x[, setdiff(colnames(x), x.names)], apply(x[, x.names, drop = F], 2, scaleFun, scaling = scaling)) }))
                                                                                                                                                                   1.
                                                                                                                                                                   gbmt::gbmt(x.names = c("RR", "TV", "Pimax", "MV", "RSBI"), unit = "PtID", time = "VentiParDays", d = 2, ng = 3, data = Dat_long, scaling = 2)
```

**Comment by alessandromagrini** [comment]
Hi there. Unfortunately, the problem is not clear from the error message. I only see that it comes from a rbind command, but I am not able to understand which one generates the error. If you can send me the data or a part of the data (even perturbed) that give the same error, I can try debugging on my system. My e-mail: alessandro.magrini@unifi.it

**Comment by zh-zhang1984** [comment]
Hi Pro. Magrini
Thank you so much for your reply.
here is the example data and I encounter the error:


mod_gbmt <- gbmt::gbmt(
  x.names=c("Pimax","MV","RSBI"#,"RR","TV"
            ),
  unit="PtID",
  time="VentiParDays", d=2, ng=3,
  data=Dat_long, scaling=1
)
Error in rbind(deparse.level, ...) : numbers of columns of arguments do not match
5.
stop("numbers of columns of arguments do not match")
4.
rbind(deparse.level, ...)
3.
(function (..., deparse.level = 1) .Internal(rbind(deparse.level, ...)))(`1` = structure(list(PtID = c("1", "1", "1"), RCCtimes = c("1", "1", "1"), VentiParDays = c(2L, 2L, 2L), RR = c(15, 15, 15), TV = c(333, 333, 333), `apply(x[, x.names, drop = F], 2, scaleFun, scaling = scaling)` = c(0, ...
2.
do.call(rbind, lapply(split(data, data[, unit]), function(x) { cbind(x[, setdiff(colnames(x), x.names)], apply(x[, x.names, drop = F], 2, scaleFun, scaling = scaling)) }))
1.
gbmt::gbmt(x.names = c("Pimax", "MV", "RSBI"), unit = "PtID", time = "VentiParDays", d = 2, ng = 3, data = Dat_long, scaling = 1)


________________________________

**Comment by alessandromagrini** [comment]
Hi there, I have uploaded a new version of the package. Please, reinstall it and check whether your application works. Note: provide a time variabile with non-duplicated time points within units (in your data, 'RCCtimes' and not 'VentiParDays').

**Comment by zh-zhang1984** [comment]
That's wonderful'

________________________________

**Comment by zh-zhang1984** [comment]
The same error seems exist:

```
library(gbmt)
Dat_long <- read.csv("/Users/zhangzhongheng/Documents/2021/TaiwanRCC/Dat_long.csv") %>% group_by(PtID) %>%
   mutate(
     VentiParDays = as.double(VentiParDays),
          VentiParDays = if_else(duplicated(VentiParDays),VentiParDays+0.5,VentiParDays)) %>% ungroup() %>% as.data.frame()
mod_gbmt <- gbmt::gbmt(
  x.names=c("Pimax","MV","RSBI","RR","TV"
            ), 
  unit="PtID", 
  time="VentiParDays", d=2, ng=2, 
  data=Dat_long, scaling=2
)
Error in rbind(deparse.level, ...) : numbers of columns of arguments do not match
```
I use a duplicated function to ensure there is no duplicated time points within a subject. 
I have updated the version with: 
`install_github("alessandromagrini/gbmt",force = T)`
____________________________

**Comment by alessandromagrini** [comment]
Hi, I suspect that you did not reinstall teh package correctly.
Using the same data, your code gives error if you use 'VentiParDays' as unit identifier (it contains duplicated values within units):

> mod_gbmt <- gbmt::gbmt(
+     x.names=c("Pimax","MV","RSBI","RR","TV"), 
+     unit="PtID", time="VentiParDays", d=2, ng=2, 
+     data=Dat_long, scaling=2)
Error in gbmt::gbmt(x.names = c("Pimax", "MV", "RSBI", "RR", "TV"), unit = "PtID",  : 
  Unit '2' has duplicated time points

But if you use 'RCCtimes' the code runs correctly:

> mod_gbmt <- gbmt::gbmt(
+     x.names=c("Pimax","MV","RSBI","RR","TV"), 
+     unit="PtID", time="RCCtimes", d=2, ng=2, 
+     data=Dat_long, scaling=2)
 EM iteration 37. Log likelihood: -1381.7664 

If the problem persist, try to delete the fold 'gbmt' in your R package installation folder and reinstall again.

**Comment by alessandromagrini** [comment]
The 'gbmt' package is now available on CRAN: [](https://cran.r-project.org/web/packages/gbmt/index.html)
You can install it by typing:
> install.packages("gbmt")

**Comment by zh-zhang1984** [comment]
Yes, this version can successfully run on my example. thank you for the excellent package.
